[package]
name = "opencv_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.84.5"
tokio = { version = "1.32.0", default-features = false, features = ["rt-multi-thread", "macros"] }